/**
 * @fileoverview Mock data for StudyPixel-GPT demonstration and development
 * 
 * This file contains realistic mock data for all entities in the system:
 * - User accounts (Admin, Teacher, Student) with demo credentials
 * - PixelBot configurations (AI tutors) with mastery statistics
 * - Student profiles with performance metrics
 * - MCQ question bank for assessment modes
 * 
 * Why: Having centralized mock data enables:
 * - Easy demonstration without backend infrastructure
 * - Rapid prototyping and UI development
 * - Consistent test data across the application
 * - Simple switching to real API endpoints (just replace imports)
 * 
 * How to replace: For production, replace these imports with API service calls
 * that fetch real data from Firebase/backend. The data structure should remain
 * the same for seamless integration.
 */

"use strict";

/**
 * Mock user accounts for authentication demonstration
 * 
 * Demo Credentials:
 * - Admin: admin@studypixel.com / admin123
 * - Teacher: teacher@studypixel.com / teacher123
 * - Student: student@studypixel.com / student123
 * 
 * Structure matches expected backend user schema
 * 
 * @constant {Array<Object>} mockUsers
 * @property {number} id - Unique user identifier
 * @property {string} email - User email (login username)
 * @property {string} password - User password (plaintext for demo - use hashing in production!)
 * @property {string} role - User role: "admin", "teacher", or "student"
 * @property {string} name - Display name
 */
const mockUsers = [
  { 
    id: 1, 
    email: "admin@studypixel.com", 
    password: "admin123", 
    role: "admin", 
    name: "System Admin" 
  },
  { 
    id: 2, 
    email: "teacher@studypixel.com", 
    password: "teacher123", 
    role: "teacher", 
    name: "Prof. Smith" 
  },
  { 
    id: 3, 
    email: "student@studypixel.com", 
    password: "student123", 
    role: "student", 
    name: "Alex Johnson" 
  },
];

/**
 * Mock PixelBot library - AI tutors with configurations and statistics
 * 
 * PixelBots are AI-powered adaptive tutors for specific subjects.
 * Each tracks mastery levels and student assignments.
 * 
 * @constant {Array<Object>} mockPixelBots
 * @property {number} id - Unique PixelBot identifier
 * @property {string} name - PixelBot display name (typically: Subject + Level)
 * @property {string} topic - Subject area category
 * @property {number} assignedStudents - Count of students using this PixelBot
 * @property {number} mastery - Average mastery level across all students (0-1 scale)
 * @property {string} class - Primary class assignment (for teacher organization)
 */
const mockPixelBots = [
  { 
    id: 1, 
    name: "Algebra Fundamentals", 
    topic: "Mathematics", 
    assignedStudents: 15, 
    mastery: 0.72, 
    class: "Grade 10A" 
  },
  { 
    id: 2, 
    name: "Networking Basics", 
    topic: "Computer Science", 
    assignedStudents: 12, 
    mastery: 0.85, 
    class: "Grade 11B" 
  },
  { 
    id: 3, 
    name: "Operating Systems", 
    topic: "Computer Science", 
    assignedStudents: 8, 
    mastery: 0.68, 
    class: "Grade 12C" 
  },
  { 
    id: 4, 
    name: "Cybersecurity", 
    topic: "Computer Science", 
    assignedStudents: 10, 
    mastery: 0.78, 
    class: "Grade 12C" 
  },
];

/**
 * Mock student profiles with performance data
 * 
 * Used by admin/teacher dashboards for monitoring and analytics.
 * In production, this would come from database queries with real-time updates.
 * 
 * @constant {Array<Object>} mockStudents
 * @property {number} id - Unique student identifier
 * @property {string} name - Student display name
 * @property {string} email - Student contact email
 * @property {string} teacher - Assigned teacher name (for grouping)
 * @property {number} avgMastery - Average mastery across all subjects (0-1 scale)
 */
const mockStudents = [
  { 
    id: 3, 
    name: "Alex Johnson", 
    email: "alex@study.com", 
    teacher: "Prof. Smith", 
    avgMastery: 0.75 
  },
  { 
    id: 4, 
    name: "Sam Lee", 
    email: "sam@study.com", 
    teacher: "Prof. Smith", 
    avgMastery: 0.82 
  },
  { 
    id: 5, 
    name: "Jordan Taylor", 
    email: "jordan@study.com", 
    teacher: "Prof. Davis", 
    avgMastery: 0.68 
  },
];

/**
 * Mock MCQ (Multiple Choice Question) bank for assessment mode
 * 
 * Questions are organized by subject and used in the PixelBot workspace
 * for knowledge assessment. Structure follows standard MCQ format with
 * 4 options (A-D) and single correct answer.
 * 
 * In production, questions would be:
 * - Fetched from database based on subject/difficulty
 * - Dynamically generated by LLM based on learning objectives
 * - Tagged with cognitive level (Bloom's taxonomy)
 * 
 * @constant {Array<Object>} mockMCQQuestions
 * @property {number} id - Unique question identifier
 * @property {string} subject - Subject/topic area (matches PixelBot name)
 * @property {string} question - Question text
 * @property {Array<Object>} options - Answer choices array
 * @property {string} options[].id - Option label (A, B, C, D)
 * @property {string} options[].text - Option text content
 * @property {string} correctAnswer - Correct option ID (A, B, C, or D)
 */
const mockMCQQuestions = [
  {
    id: 1,
    subject: "Networking Basics",
    question: "What is the primary function of TCP in networking?",
    options: [
      { id: "A", text: "Data encryption" },
      { id: "B", text: "Reliable data transmission" },
      { id: "C", text: "IP address assignment" },
      { id: "D", text: "Network routing" }
    ],
    correctAnswer: "B"
  },
  {
    id: 2,
    subject: "Networking Basics",
    question: "Which OSI layer is responsible for end-to-end communication?",
    options: [
      { id: "A", text: "Physical Layer" },
      { id: "B", text: "Data Link Layer" },
      { id: "C", text: "Transport Layer" },
      { id: "D", text: "Application Layer" }
    ],
    correctAnswer: "C"
  },
  {
    id: 3,
    subject: "Operating Systems",
    question: "What is the main purpose of virtual memory?",
    options: [
      { id: "A", text: "To increase CPU speed" },
      { id: "B", text: "To allow programs larger than physical RAM" },
      { id: "C", text: "To encrypt data storage" },
      { id: "D", text: "To manage network connections" }
    ],
    correctAnswer: "B"
  },
  {
    id: 4,
    subject: "Algebra Fundamentals",
    question: "What is the solution to the equation 2x + 5 = 13?",
    options: [
      { id: "A", text: "x = 3" },
      { id: "B", text: "x = 4" },
      { id: "C", text: "x = 5" },
      { id: "D", text: "x = 6" }
    ],
    correctAnswer: "B"
  },
  {
    id: 5,
    subject: "Cybersecurity",
    question: "What type of attack involves overwhelming a system with traffic?",
    options: [
      { id: "A", text: "Phishing" },
      { id: "B", text: "SQL Injection" },
      { id: "C", text: "DDoS Attack" },
      { id: "D", text: "Man-in-the-Middle" }
    ],
    correctAnswer: "C"
  }
];

// Export all mock data for use throughout the application
export {
  mockUsers,
  mockPixelBots,
  mockStudents,
  mockMCQQuestions
};